apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: regassist.azurecr.io/backend-java
    newTag: $TAG

commonLabels:
  app: backend-java
  environment: prd
