apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: regassist.azurecr.io/frontend-vue
    newTag: {{TAG}}

commonLabels:
  app: frontend-vue
  environment: dev



