apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: regassist.azurecr.io/backend-java # 이미지 주소 변경필요
    newTag: main-20241007052920

commonLabels:
  app: backend-java
  environment: dev
